
server:
  log_level: debug
  http_listen_port: 12345
  
traces:
  configs:
  - name: default
    service_graphs:
      enabled: true  
    automatic_logging:
      backend: stdout
      roots: true
    remote_write:
      - endpoint: tempo-us-central1.grafana.net:443
        basic_auth:
          username: 406010
          password: eyJrIjoiNGRjNDU3MmQ1MTVlOTk2ODQ1Zjk1MGNmZDcwNGQyMmIwOGEwNjA3MyIsIm4iOiJyb2dtZW4tcHVibGlzaGVyIiwiaWQiOjgxNDMyMn0=
    receivers:
      otlp:
        protocols:
          grpc:

