profile=local
GRADLE_RUN_COMMAND=./gradlew bootRun -Dspring.profiles.active=$(profile) $(JVM_ARG)



builder:
	$(DOCKER_RUN_COMMAND) gradlew assemble $(ARG)


docker-build: builder
	docker build -f ci/docker/Dockerfile.otelv1  -t rmendoza/ms-services-app-m4:v1.1 .


docker-build-v2: builder
	docker build -f ci/docker/Dockerfile.otelv2  -t rmendoza/ms-services-app-m4:v2.1 .

docker-run: docker-build
	docker run --name api --rm -e SPRING_PROFILE=${SPRING_PROFILE}  \
		-p 8080:8080 -p 5005:5005 \
		 rmendoza/ms-services-app-m4:v1.1

compose-run: docker-build
	docker-compose -f ci/compose/docker-compose.yaml up

compose-run-alloy: docker-build
	docker-compose -f ci/compose/docker-compose-alloy.yaml up	