version: "3.4"
services:
 
  ms-service-app-ms4.applications.svc.cluster.local:
    build:
      context: .
      dockerfile: ci/docker/Dockerfile
    environment:
      - APP_NAME=ms-service-app-ms4
      - JAVA_TOOL_OPTIONS= -Dspring.profiles.active=local -Dotel.instrumentation.http.server.capture-request-headers=X-Tenant-ID -Dotel.javaagent.extensions=otel-custom-extractor-1.0.0.jar -Dotel.instrumentation.servlet.experimental-span-attributes=true -DCUSTOM_HEADER_NAME=X-Tenant-ID -Dotel.instrumentation.http.server.capture-request-headers=X-Tenant-ID -Dotel.instrumentation.servlet.capture-headers=X-Tenant-ID -Dotel.instrumentation.common.default-enabled=true -Dotel.instrumentation.micrometer.enabled=true -Dotel.instrumentation.common-metrics.enabled=true -Dotel.instrumentation.common.default-enabled=true -Dotel.instrumentation.servlet-metrics.enabled=true -Dotel.instrumentation.common.enabled=true -Dotel.instrumentation.runtime-telemetry.enabled=true	  
      - OTEL_SERVICE_NAME=ms-service-app-ms4
      - OTEL_INSTRUMENTATION_MICROMETER_ENABLED=true
      - OTEL_INSTRUMENTATION_APACHE_HTTPCLIENT_ENABLED=true
      - OTEL_INSTRUMENTATION_SPRING_WEB_ENABLED=true
      - OTEL_INSTRUMENTATION_JETTY_HTTPCLIENT_ENABLED=true
      - OTEL_INSTRUMENTATION_JAVA_HTTP_CLIENT_ENABLED=true
      - OTEL_INSTRUMENTATION_HTTP_CLIENT_EMIT_EXPERIMENTAL_TELEMETRY=true 
      - OTEL_INSTRUMENTATION_HTTP_SERVER_EMIT_EXPERIMENTAL_TELEMETRY=true
      - OTEL_INSTRUMENTATION_HTTP_SERVER_CAPTURE_RESPONSE_HEADERS=X-Tenant-ID
      - OTEL_INSTRUMENTATION_HTTP_CLIENT_CAPTURE_RESPONSE_HEADERS=X-Tenant-ID
      - OTEL_INSTRUMENTATION_COMMON_METRICS_ENABLED=true
      - OTEL_INSTRUMENTATION_COMMON_DEFAULT_ENABLED=true
      - OTEL_INSTRUMENTATION_SERVLET_ENABLED=true
      - OTEL_INSTRUMENTATION_HTTP_URL_CONNECTION_ENABLED=true
      - OTEL_INSTRUMENTATION_OKHTTP_ENABLED=true
      - OTEL_JAVAAGENT_LOGGING=simple
      - OTEL_INSTRUMENTATION_JDBC_CAPTURE_EXPERIMENTAL_SPAN_ATTRIBUTES=true
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=prometheus
      - OTEL_EXPORTER_PROMETHEUS_PORT=9464
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
      - OTEL_INSTRUMENTATION_HTTP_SERVER_CAPTURE_REQUEST_HEADERS=X-Tenant-ID 
      - OTEL_INSTRUMENTATION_HTTP_CLIENT_CAPTURE_REQUEST_HEADERS=X-Tenant-ID
      - OTEL_INSTRUMENTATION_SERVLET_CAPTURE_HEADERS=X-Tenant-ID
      - OTEL_RESOURCE_ATTRIBUTES=service.name=ms-service-app-ms4,environment=production,region=us-east
    ports:
      - "8080:8080"
      - "9464:9464"	  

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:1.45
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14269:14269
      - 14250:14250
      - 9411:9411
      - 4317:4317
      - 4318:4318      