FROM openjdk:17-jdk-slim
EXPOSE 8080
WORKDIR /api
ARG JAR=ms-service-app-ms4.jar
COPY build/libs/*.jar /app.jar
COPY opentelemetry-javaagent.2.15.0.jar /opentelemetry-javaagent.jar
COPY otel-custom-extractor-1.0.0.jar /otel-custom-extractor-1.0.0.jar
ENTRYPOINT ["java",  "-javaagent:/opentelemetry-javaagent.jar", "-Dotel.javaagent.extensions=/otel-custom-extractor-1.0.0.jar","-Dotel.javaagent.extension.plugins=/otel-custom-extractor-1.0.0.jar" ,"-jar","/app.jar"]